// <auto-generated />
using System;
using KalosfideAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KalosfideAPI.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KalosfideAPI.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("ApplicationUser");
                });

            modelBuilder.Entity("KalosfideAPI.Data.ChangementEtatRole", b =>
                {
                    b.Property<string>("UtilisateurId")
                        .HasMaxLength(20);

                    b.Property<int>("RoleNo");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Etat")
                        .HasMaxLength(1);

                    b.HasKey("UtilisateurId", "RoleNo", "Date");

                    b.ToTable("JournalEtatRole");
                });

            modelBuilder.Entity("KalosfideAPI.Data.ChangementEtatUtilisateur", b =>
                {
                    b.Property<string>("UtilisateurId")
                        .HasMaxLength(20);

                    b.Property<DateTime>("Date");

                    b.Property<string>("Etat")
                        .HasMaxLength(1);

                    b.HasKey("UtilisateurId", "Date");

                    b.ToTable("JournalEtatUtilisateur");
                });

            modelBuilder.Entity("KalosfideAPI.Data.Commande", b =>
                {
                    b.Property<string>("UtilisateurId")
                        .HasMaxLength(20);

                    b.Property<int>("RoleNo");

                    b.Property<int>("No");

                    b.Property<DateTime>("Date");

                    b.Property<string>("LivraisonId")
                        .HasMaxLength(20);

                    b.Property<int?>("LivraisonNo");

                    b.Property<int?>("LivraisonNo1");

                    b.Property<int?>("LivraisonRoleNo");

                    b.Property<string>("LivraisonUtilisateurId");

                    b.HasKey("UtilisateurId", "RoleNo", "No");

                    b.HasIndex("Date");

                    b.HasIndex("LivraisonUtilisateurId", "LivraisonRoleNo", "LivraisonNo1");

                    b.ToTable("Commandes");
                });

            modelBuilder.Entity("KalosfideAPI.Data.DétailCommande", b =>
                {
                    b.Property<string>("CommandeUtilisateurId")
                        .HasMaxLength(20);

                    b.Property<int>("CommandeRoleNo");

                    b.Property<int>("CommandeNo");

                    b.Property<string>("ProduitUtilisateurId")
                        .HasMaxLength(20);

                    b.Property<int>("ProduitRoleNo");

                    b.Property<int>("ProduitNo");

                    b.Property<int>("Quantité");

                    b.HasKey("CommandeUtilisateurId", "CommandeRoleNo", "CommandeNo", "ProduitUtilisateurId", "ProduitRoleNo", "ProduitNo");

                    b.ToTable("DétailCommandes");
                });

            modelBuilder.Entity("KalosfideAPI.Data.Livraison", b =>
                {
                    b.Property<string>("UtilisateurId")
                        .HasMaxLength(20);

                    b.Property<int>("RoleNo");

                    b.Property<int>("No");

                    b.Property<DateTime>("Date");

                    b.HasKey("UtilisateurId", "RoleNo", "No");

                    b.HasIndex("Date");

                    b.ToTable("Livraisons");
                });

            modelBuilder.Entity("KalosfideAPI.Data.Produit", b =>
                {
                    b.Property<string>("UtilisateurId")
                        .HasMaxLength(20);

                    b.Property<int>("RoleNo");

                    b.Property<int>("No");

                    b.Property<string>("Description")
                        .HasMaxLength(500);

                    b.Property<bool>("Indisponible");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("UtilisateurId", "RoleNo", "No");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("Produits");
                });

            modelBuilder.Entity("KalosfideAPI.Data.Role", b =>
                {
                    b.Property<string>("UtilisateurId")
                        .HasMaxLength(20);

                    b.Property<int>("RoleNo");

                    b.Property<string>("Adresse")
                        .HasMaxLength(500);

                    b.Property<string>("Etat")
                        .HasMaxLength(1);

                    b.Property<string>("FournisseurId")
                        .HasMaxLength(20);

                    b.Property<long?>("FournisseurRoleNo");

                    b.Property<int?>("FournisseurRoleNo1");

                    b.Property<string>("FournisseurUtilisateurId");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(1);

                    b.HasKey("UtilisateurId", "RoleNo");

                    b.HasIndex("FournisseurId");

                    b.HasIndex("Nom");

                    b.HasIndex("Type");

                    b.HasIndex("FournisseurUtilisateurId", "FournisseurRoleNo1");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("KalosfideAPI.Data.Utilisateur", b =>
                {
                    b.Property<string>("UtilisateurId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20);

                    b.Property<string>("Etat")
                        .HasMaxLength(1);

                    b.Property<int>("RoleSélectionnéNo");

                    b.Property<int?>("RoleSélectionnéRoleNo");

                    b.Property<string>("RoleSélectionnéUtilisateurId");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("UtilisateurId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("RoleSélectionnéUtilisateurId", "RoleSélectionnéRoleNo");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("KalosfideAPI.SiteInfos.SiteInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Date")
                        .HasMaxLength(4);

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Titre")
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.ToTable("SiteInfos");

                    b.HasData(
                        new { Id = 1L, Date = "2018", Nom = "kalofide.fr", Titre = "Kalosfide" }
                    );
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("KalosfideAPI.Data.ChangementEtatRole", b =>
                {
                    b.HasOne("KalosfideAPI.Data.Role", "Role")
                        .WithMany("ChangementsEtat")
                        .HasForeignKey("UtilisateurId", "RoleNo")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("KalosfideAPI.Data.ChangementEtatUtilisateur", b =>
                {
                    b.HasOne("KalosfideAPI.Data.Utilisateur", "Utilisateur")
                        .WithMany("ChangementsEtat")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("KalosfideAPI.Data.Commande", b =>
                {
                    b.HasOne("KalosfideAPI.Data.Role", "Client")
                        .WithMany("Commandes")
                        .HasForeignKey("UtilisateurId", "RoleNo")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KalosfideAPI.Data.Livraison", "Livraison")
                        .WithMany("Commandes")
                        .HasForeignKey("LivraisonUtilisateurId", "LivraisonRoleNo", "LivraisonNo1");
                });

            modelBuilder.Entity("KalosfideAPI.Data.DétailCommande", b =>
                {
                    b.HasOne("KalosfideAPI.Data.Commande", "Commande")
                        .WithMany("DétailCommandes")
                        .HasForeignKey("CommandeUtilisateurId", "CommandeRoleNo", "CommandeNo")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KalosfideAPI.Data.Produit", "Produit")
                        .WithMany()
                        .HasForeignKey("CommandeUtilisateurId", "CommandeRoleNo", "CommandeNo");
                });

            modelBuilder.Entity("KalosfideAPI.Data.Livraison", b =>
                {
                    b.HasOne("KalosfideAPI.Data.Role", "Livreur")
                        .WithMany("Livraisons")
                        .HasForeignKey("UtilisateurId", "RoleNo")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("KalosfideAPI.Data.Produit", b =>
                {
                    b.HasOne("KalosfideAPI.Data.Role", "Producteur")
                        .WithMany("Produits")
                        .HasForeignKey("UtilisateurId", "RoleNo")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("KalosfideAPI.Data.Role", b =>
                {
                    b.HasOne("KalosfideAPI.Data.Utilisateur", "Utilisateur")
                        .WithMany("Roles")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KalosfideAPI.Data.Role", "Fournisseur")
                        .WithMany("Clients")
                        .HasForeignKey("FournisseurUtilisateurId", "FournisseurRoleNo1");
                });

            modelBuilder.Entity("KalosfideAPI.Data.Utilisateur", b =>
                {
                    b.HasOne("KalosfideAPI.Data.ApplicationUser", "ApplicationUser")
                        .WithOne("Utilisateur")
                        .HasForeignKey("KalosfideAPI.Data.Utilisateur", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KalosfideAPI.Data.Role", "RoleSélectionné")
                        .WithMany()
                        .HasForeignKey("RoleSélectionnéUtilisateurId", "RoleSélectionnéRoleNo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("KalosfideAPI.Data.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("KalosfideAPI.Data.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KalosfideAPI.Data.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("KalosfideAPI.Data.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
